"""
Dungeon - A TUI-based roguelike game
"""

__version__ = "1.0.0"

# Core game engine
from dungeon.engine import GameEngine
from dungeon.map import Map, Rect, Tile, TileType
from dungeon.save_system import save_system, SaveSystem, SaveSlot, PersistentContext
from dungeon.storylets import storylet_system, Storylet, StoryletSystem
from dungeon.network import (
    MultiplayerClient,
    MultiplayerServer,
    GameState,
    MessageType,
    encode_message,
    decode_message,
)

# Main entities
from dungeon.entities import (
    AbjurationSpell,
    AbsorbEffect,
    AIState,
    ActionResult,
    BarrierEffect,
    BaseAI,
    BaseComponent,
    BurnEffect,
    CharmEffect,
    ChronomancySpell,
    ConfusedAI,
    ConfusionEffect,
    Consumable,
    ConjurationSpell,
    CurseEffect,
    CurioMerchant,
    DecayEffect,
    Entity,
    Equipment,
    Equippable,
    EvocationSpell,
    FearEffect,
    FleeAI,
    Fighter,
    FreezeEffect,
    GoldConsumable,
    HasteEffect,
    HealingConsumable,
    HostileAI,
    Inventory,
    Item,
    Level,
    LightningConsumable,
    LoreSystem,
    MagicArmorEffect,
    MagicConsumable,
    ManaRestorationConsumable,
    ManaSystem,
    MentomancySpell,
    Monster,
    NecromancySpell,
    Pathfinder,
    Player,
    PoisonEffect,
    RangedAI,
    RegenEffect,
    ReflectEffect,
    SlowEffect,
    Spell,
    SpellSchool,
    Stairs,
    StatusEffect,
    StatusEffectManager,
    StunEffect,
    TransmutationSpell,
    WetEffect,
    can_see,
    chebyshev_distance,
    direction_toward,
    euclidean_distance,
)

__all__ = [
    # Core
    "GameEngine",
    "Map",
    "Rect",
    "Tile",
    "TileType",
    "save_system",
    "SaveSystem",
    "SaveSlot",
    "PersistentContext",
    "storylet_system",
    "Storylet",
    "StoryletSystem",
    # Network
    "MultiplayerClient",
    "MultiplayerServer",
    "GameState",
    "MessageType",
    "encode_message",
    "decode_message",
    # Entities
    "Entity",
    "Player",
    "Monster",
    "Item",
    "Stairs",
    "BaseComponent",
    "Fighter",
    "Equipment",
    "Inventory",
    "Level",
    "Consumable",
    "Equippable",
    # AI
    "BaseAI",
    "HostileAI",
    "ConfusedAI",
    "RangedAI",
    "PatrolAI",
    "FleeAI",
    "StunnedAI",
    "StateMachineAI",
    "AIState",
    "ActionResult",
    "Pathfinder",
    # AI utilities
    "chebyshev_distance",
    "euclidean_distance",
    "direction_toward",
    "can_see",
    # Status effects
    "StatusEffect",
    "StatusEffectManager",
    "BurnEffect",
    "PoisonEffect",
    "FreezeEffect",
    "WetEffect",
    "StunEffect",
    "RegenEffect",
    "HasteEffect",
    "SlowEffect",
    "DecayEffect",
    "FearEffect",
    "CharmEffect",
    "ConfusionEffect",
    "BarrierEffect",
    "ReflectEffect",
    "AbsorbEffect",
    "MagicArmorEffect",
    "CurseEffect",
    # Spells
    "Spell",
    "SpellSchool",
    "TransmutationSpell",
    "EvocationSpell",
    "ChronomancySpell",
    "MentomancySpell",
    "ConjurationSpell",
    "AbjurationSpell",
    "NecromancySpell",
    "ManaSystem",
    "MagicConsumable",
    # Consumables
    "HealingConsumable",
    "LightningConsumable",
    "ConfusionConsumable",
    "GoldConsumable",
    "ManaRestorationConsumable",
    # Special entities
    "LoreSystem",
    "Shrine",
    "CurioMerchant",
]
